### ISSUE TITLE
undefined is not a function (evaluating 'string.toLowerCase()')

### ISSUE THREAD

**Issue by justinireland** [mattyork/fuzzy#27]
I'm getting the error with the following trace:
match
fuzzy.js: 50

<unkown>
fuzzy.js: 120

filter
fuzzy.js :115

as soon as I try to filter for even a single character. I've verified my input is a string and the list I'm filtering against is an array of objects with only string values.

Sorry I cannot cut and paste the error msgs as I'm using this in a React Native app and the error is reported in the Android emulator.

**Comment by nicolaerusan** [comment]
Hit the same issue :)

**Comment by mattyork** [comment]
I'm assuming this is an issue with using the keyword "string". Changing the var name. We'll see if that works.

**Comment by justinireland** [comment]
I updated and now I'm getting the same error except 'str.toLowerCase()'

Maybe lets confirm the issue is fixed before closing it.
