### ISSUE TITLE
Angluar2 Ionic

### ISSUE THREAD

**Issue by ghost** [mattyork/fuzzy#32]
Hi, 

I try to use your lib with ionic2 

npm install https://github.com/mattyork/fuzzy.git#typescript --save

import { fuzzy }   from 'fuzzy';

error
throw new Error("Cannot find module \"fuzzy\"");

any idea ?

thx

**Comment by ghost** [comment]
And if I try with master branch.

npm install fuzzy --save

error
/node_modules/fuzzy/lib/fuzzy"' has no exported member 'fuzzy'.

**Comment by SamVerschueren** [comment]
I used it in my Angular 2 application and it works great. It might have something to do with your import statement.

```
$ npm install fuzzy --save
```

```js
import { filter } from 'fuzzy';

const list = ['baconing', 'narwhal', 'a mighty bear canoe'];
const results = filter('bcn', list)
```

Or, you can also do it like this probably

```js
import * as fuzzy from 'fuzzy';

const list = ['baconing', 'narwhal', 'a mighty bear canoe'];
const results = fuzzy.filter('bcn', list)
```
