### ISSUE TITLE
Examples broken?

### ISSUE THREAD

**Issue by knod** [mattyork/fuzzy#8]
In disney.html, the matching letters don't turn bold until the next key is pressed.

In directors.html, if I type in "ee", it seems like the only matches brought up are ones with that exact match. No words appear in which there are two e's that are not consecutive. That might be because there's some limit on the number of matches shown. I haven't yet figured out how to find that setting.

**Comment by mattyork** [comment]
@knod, thanks for opening the issue!

The disney.html issue is fixed in 857f9df40b161848f7218833dba67614ea8f324a.

In directors.html, you are correct that there are only a limited number shown (50 in this case). Right under the search box there is text that says "displaying 50 of 54135"
